# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    {
                        size: [200, 400]
                        mode: outbound
                    }

        trombi_square:
            quality: 75
            filters:
                scale:
                    {
                        dim: [300, 300]
                    }
                background:
                    size: [300, 300]
                    color: '#ffffff'
                    position: center