vich_uploader:
    db_driver: orm

    mappings:
        picture_file:
            uri_prefix: /uploads/profile/picture
            upload_destination: '%upload_directory%/profile/picture'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        method_picture:
            uri_prefix: /uploads/method/picture
            upload_destination: '%upload_directory%/method/picture'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
